# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-21 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('_lowername', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.CharField(blank=True, max_length=150)),
                ('buckets', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('collaborators', models.ManyToManyField(blank=True, to='Innovation.Collaborator')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
